#!/bin/bash
# Mac/Linux script to run TSDetect in headless mode from the command line
# RUN
#    ./tsdetect /relative_path_to_project/
# OR
#    sh tsdetect /relative_path_to_project/

#EXAMPLE    sh tsdetect /absolute/path/to/project

./gradlew -q -Dorg.gradle.jvmargs="-Djava.awt.headless=true" runIde --console=plain --warning-mode=none -Ppaths="$*"