version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tsdetect
    ports:
      - "3308:3306"
    networks:
      - tsdetect-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - tsdetect-network
networks:
  tsdetect-network:
    name: tsdetect-network
    driver: bridge
volumes:
  db:
    driver: local